/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AbdullakhAboutMeSection, } from "./components/cnt-flexy-view-abdullakh-promo-header-wrapper/res/view/cnt-flexy-view-abdullakh-promo-header-presentation/res/view/cnt-flexy-view-abdullakh-promo-about-me-section/interface/common.interface";
import { AbdullakhExperiments, } from "./components/cnt-flexy-view-abdullakh-promo-experiments-wrapper/res/view/cnt-flexy-view-abdullakh-promo-experiments/interface/common.interface";
import { AbdullakhExperimentsBlocks, } from "./components/cnt-flexy-view-abdullakh-promo-experiments-wrapper/res/view/cnt-flexy-view-abdullakh-promo-experiments/res/view/cnt-flexy-view-abdullakh-promo-experiments-blocks/interface/common.interface";
import { AbdullakhFooter, } from "./components/cnt-flexy-view-abdullakh-promo-footer-wrapper/res/view/cnt-flexy-view-abdullakh-promo-footer/interface/common.interface";
import { AbdullakhHeaderNav, AbdullakhHeaderNavSocial, } from "./components/cnt-flexy-view-abdullakh-promo-header-wrapper/res/view/cnt-flexy-view-abdullakh-promo-header-presentation/res/view/cnt-flexy-view-abdullakh-promo-header-nav/interface/common.interface";
import { AbdullakhHeaderPresentation, } from "./components/cnt-flexy-view-abdullakh-promo-header-wrapper/res/view/cnt-flexy-view-abdullakh-promo-header-presentation/interface/common.interface";
import { AbdullakhLatestWorks, } from "./components/cnt-flexy-view-abdullakh-promo-latest-works-wrapper/res/view/cnt-flexy-view-abdullakh-promo-latest-works/interface/common.interface";
import { AbdullakhLatestWorksBlocks, } from "./components/cnt-flexy-view-abdullakh-promo-latest-works-wrapper/res/view/cnt-flexy-view-abdullakh-promo-latest-works/res/view/cnt-flexy-view-abdullakh-promo-latest-works-block/interface/common.interface";
import { AbdullakhSectionAboutMe, } from "./components/cnt-flexy-view-abdullakh-promo-header-wrapper/res/view/cnt-flexy-view-abdullakh-promo-header-presentation/res/view/cnt-flexy-view-abdullakh-promo-about-me-section/res/view/cnt-flexy-view-abdullakh-promo-section-about-me/interface/common.interface";
import { AbdullakhSectionForm, } from "./components/cnt-flexy-view-abdullakh-promo-header-wrapper/res/view/cnt-flexy-view-abdullakh-promo-header-presentation/res/view/cnt-flexy-view-abdullakh-promo-about-me-section/res/view/cnt-flexy-view-abdullakh-promo-section-form/interface/common.interface";
export namespace Components {
    interface CntFlexyViewAbdullakhPromoAboutMeSection {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "about": AbdullakhAboutMeSection;
    }
    interface CntFlexyViewAbdullakhPromoAnimateBtn {
        "arr": any;
    }
    interface CntFlexyViewAbdullakhPromoExperiments {
        /**
          * массив для вывода элементов Experiments
         */
        "payload": AbdullakhExperiments;
    }
    interface CntFlexyViewAbdullakhPromoExperimentsBlocks {
        /**
          * массив для вывода элементов ExperimentsBlocks
         */
        "arr": AbdullakhExperimentsBlocks;
    }
    interface CntFlexyViewAbdullakhPromoExperimentsWrapper1_01 {
        /**
          * префикс путь к картинкам
         */
        "pathToAssets": string;
        /**
          * массив для вывода элементов Experiments
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhPromoFooter {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories": AbdullakhFooter;
    }
    interface CntFlexyViewAbdullakhPromoFooterNav {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhPromoFooterWrapper1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories": any;
        /**
          * префикс путь к картинкам
         */
        "pathToAssets": string;
    }
    interface CntFlexyViewAbdullakhPromoFormClose {
    }
    interface CntFlexyViewAbdullakhPromoHeaderNav {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "headNav": AbdullakhHeaderNav;
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "social": AbdullakhHeaderNavSocial;
    }
    interface CntFlexyViewAbdullakhPromoHeaderPresentation {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories": AbdullakhHeaderPresentation;
    }
    interface CntFlexyViewAbdullakhPromoHeaderSocialIcon {
        "icon": AbdullakhHeaderNavSocial;
    }
    interface CntFlexyViewAbdullakhPromoHeaderWrapper1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories": any;
        /**
          * префикс путь к картинкам
         */
        "pathToAssets": string;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorks {
        /**
          * массив для вывода элементов LatestWorks
         */
        "payload": AbdullakhLatestWorks;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorksBlock {
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "arr": AbdullakhLatestWorksBlocks;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorksWrapper1_01 {
        /**
          * префикс путь к картинкам
         */
        "pathToAssets": string;
        /**
          * массив для вывода элементов LatestWorksWrapper
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhPromoSectionAboutMe {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "about": AbdullakhSectionAboutMe;
    }
    interface CntFlexyViewAbdullakhPromoSectionForm {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "contactForm": AbdullakhSectionForm;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement extends Components.CntFlexyViewAbdullakhPromoAboutMeSection, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement;
        new (): HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement extends Components.CntFlexyViewAbdullakhPromoAnimateBtn, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement;
        new (): HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoExperimentsElement extends Components.CntFlexyViewAbdullakhPromoExperiments, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoExperimentsElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoExperimentsElement;
        new (): HTMLCntFlexyViewAbdullakhPromoExperimentsElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement extends Components.CntFlexyViewAbdullakhPromoExperimentsBlocks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement;
        new (): HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element extends Components.CntFlexyViewAbdullakhPromoExperimentsWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element;
        new (): HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhPromoFooterElement extends Components.CntFlexyViewAbdullakhPromoFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoFooterElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoFooterElement;
        new (): HTMLCntFlexyViewAbdullakhPromoFooterElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoFooterNavElement extends Components.CntFlexyViewAbdullakhPromoFooterNav, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoFooterNavElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoFooterNavElement;
        new (): HTMLCntFlexyViewAbdullakhPromoFooterNavElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element extends Components.CntFlexyViewAbdullakhPromoFooterWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element;
        new (): HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhPromoFormCloseElement extends Components.CntFlexyViewAbdullakhPromoFormClose, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoFormCloseElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoFormCloseElement;
        new (): HTMLCntFlexyViewAbdullakhPromoFormCloseElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoHeaderNavElement extends Components.CntFlexyViewAbdullakhPromoHeaderNav, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoHeaderNavElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoHeaderNavElement;
        new (): HTMLCntFlexyViewAbdullakhPromoHeaderNavElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement extends Components.CntFlexyViewAbdullakhPromoHeaderPresentation, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement;
        new (): HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement extends Components.CntFlexyViewAbdullakhPromoHeaderSocialIcon, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement;
        new (): HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element extends Components.CntFlexyViewAbdullakhPromoHeaderWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element;
        new (): HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhPromoLatestWorksElement extends Components.CntFlexyViewAbdullakhPromoLatestWorks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoLatestWorksElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoLatestWorksElement;
        new (): HTMLCntFlexyViewAbdullakhPromoLatestWorksElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement extends Components.CntFlexyViewAbdullakhPromoLatestWorksBlock, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement;
        new (): HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element extends Components.CntFlexyViewAbdullakhPromoLatestWorksWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element;
        new (): HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement extends Components.CntFlexyViewAbdullakhPromoSectionAboutMe, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement;
        new (): HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement;
    };
    interface HTMLCntFlexyViewAbdullakhPromoSectionFormElement extends Components.CntFlexyViewAbdullakhPromoSectionForm, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhPromoSectionFormElement: {
        prototype: HTMLCntFlexyViewAbdullakhPromoSectionFormElement;
        new (): HTMLCntFlexyViewAbdullakhPromoSectionFormElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-abdullakh-promo-about-me-section": HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement;
        "cnt-flexy-view-abdullakh-promo-animate-btn": HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement;
        "cnt-flexy-view-abdullakh-promo-experiments": HTMLCntFlexyViewAbdullakhPromoExperimentsElement;
        "cnt-flexy-view-abdullakh-promo-experiments-blocks": HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement;
        "cnt-flexy-view-abdullakh-promo-experiments-wrapper-1_01": HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element;
        "cnt-flexy-view-abdullakh-promo-footer": HTMLCntFlexyViewAbdullakhPromoFooterElement;
        "cnt-flexy-view-abdullakh-promo-footer-nav": HTMLCntFlexyViewAbdullakhPromoFooterNavElement;
        "cnt-flexy-view-abdullakh-promo-footer-wrapper-1_01": HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element;
        "cnt-flexy-view-abdullakh-promo-form-close": HTMLCntFlexyViewAbdullakhPromoFormCloseElement;
        "cnt-flexy-view-abdullakh-promo-header-nav": HTMLCntFlexyViewAbdullakhPromoHeaderNavElement;
        "cnt-flexy-view-abdullakh-promo-header-presentation": HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement;
        "cnt-flexy-view-abdullakh-promo-header-social-icon": HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement;
        "cnt-flexy-view-abdullakh-promo-header-wrapper-1_01": HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element;
        "cnt-flexy-view-abdullakh-promo-latest-works": HTMLCntFlexyViewAbdullakhPromoLatestWorksElement;
        "cnt-flexy-view-abdullakh-promo-latest-works-block": HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement;
        "cnt-flexy-view-abdullakh-promo-latest-works-wrapper-1_01": HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element;
        "cnt-flexy-view-abdullakh-promo-section-about-me": HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement;
        "cnt-flexy-view-abdullakh-promo-section-form": HTMLCntFlexyViewAbdullakhPromoSectionFormElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewAbdullakhPromoAboutMeSection {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "about"?: AbdullakhAboutMeSection;
        /**
          * Вызов модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhPromoAnimateBtn {
        "arr"?: any;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhPromoExperiments {
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnExperiments"?: (event: CustomEvent<any>) => void;
        /**
          * массив для вывода элементов Experiments
         */
        "payload"?: AbdullakhExperiments;
    }
    interface CntFlexyViewAbdullakhPromoExperimentsBlocks {
        /**
          * массив для вывода элементов ExperimentsBlocks
         */
        "arr"?: AbdullakhExperimentsBlocks;
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnExperiments"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhPromoExperimentsWrapper1_01 {
        /**
          * префикс путь к картинкам
         */
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов Experiments
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhPromoFooter {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories"?: AbdullakhFooter;
    }
    interface CntFlexyViewAbdullakhPromoFooterNav {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "arr"?: any;
    }
    interface CntFlexyViewAbdullakhPromoFooterWrapper1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories"?: any;
        /**
          * префикс путь к картинкам
         */
        "pathToAssets"?: string;
    }
    interface CntFlexyViewAbdullakhPromoFormClose {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        /**
          * Закрытие модального окна формы
         */
        "onOpMenu"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhPromoHeaderNav {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "headNav"?: AbdullakhHeaderNav;
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "social"?: AbdullakhHeaderNavSocial;
    }
    interface CntFlexyViewAbdullakhPromoHeaderPresentation {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories"?: AbdullakhHeaderPresentation;
    }
    interface CntFlexyViewAbdullakhPromoHeaderSocialIcon {
        "icon"?: AbdullakhHeaderNavSocial;
    }
    interface CntFlexyViewAbdullakhPromoHeaderWrapper1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "categories"?: any;
        /**
          * префикс путь к картинкам
         */
        "pathToAssets"?: string;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorks {
        /**
          * массив для вывода элементов LatestWorks
         */
        "payload"?: AbdullakhLatestWorks;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorksBlock {
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "arr"?: AbdullakhLatestWorksBlocks;
    }
    interface CntFlexyViewAbdullakhPromoLatestWorksWrapper1_01 {
        /**
          * префикс путь к картинкам
         */
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов LatestWorksWrapper
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhPromoSectionAboutMe {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "about"?: AbdullakhSectionAboutMe;
        /**
          * close модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhPromoSectionForm {
        /**
          * объект с массивом меню и string для подкомпонентов
         */
        "contactForm"?: AbdullakhSectionForm;
        /**
          * close модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-abdullakh-promo-about-me-section": CntFlexyViewAbdullakhPromoAboutMeSection;
        "cnt-flexy-view-abdullakh-promo-animate-btn": CntFlexyViewAbdullakhPromoAnimateBtn;
        "cnt-flexy-view-abdullakh-promo-experiments": CntFlexyViewAbdullakhPromoExperiments;
        "cnt-flexy-view-abdullakh-promo-experiments-blocks": CntFlexyViewAbdullakhPromoExperimentsBlocks;
        "cnt-flexy-view-abdullakh-promo-experiments-wrapper-1_01": CntFlexyViewAbdullakhPromoExperimentsWrapper1_01;
        "cnt-flexy-view-abdullakh-promo-footer": CntFlexyViewAbdullakhPromoFooter;
        "cnt-flexy-view-abdullakh-promo-footer-nav": CntFlexyViewAbdullakhPromoFooterNav;
        "cnt-flexy-view-abdullakh-promo-footer-wrapper-1_01": CntFlexyViewAbdullakhPromoFooterWrapper1_01;
        "cnt-flexy-view-abdullakh-promo-form-close": CntFlexyViewAbdullakhPromoFormClose;
        "cnt-flexy-view-abdullakh-promo-header-nav": CntFlexyViewAbdullakhPromoHeaderNav;
        "cnt-flexy-view-abdullakh-promo-header-presentation": CntFlexyViewAbdullakhPromoHeaderPresentation;
        "cnt-flexy-view-abdullakh-promo-header-social-icon": CntFlexyViewAbdullakhPromoHeaderSocialIcon;
        "cnt-flexy-view-abdullakh-promo-header-wrapper-1_01": CntFlexyViewAbdullakhPromoHeaderWrapper1_01;
        "cnt-flexy-view-abdullakh-promo-latest-works": CntFlexyViewAbdullakhPromoLatestWorks;
        "cnt-flexy-view-abdullakh-promo-latest-works-block": CntFlexyViewAbdullakhPromoLatestWorksBlock;
        "cnt-flexy-view-abdullakh-promo-latest-works-wrapper-1_01": CntFlexyViewAbdullakhPromoLatestWorksWrapper1_01;
        "cnt-flexy-view-abdullakh-promo-section-about-me": CntFlexyViewAbdullakhPromoSectionAboutMe;
        "cnt-flexy-view-abdullakh-promo-section-form": CntFlexyViewAbdullakhPromoSectionForm;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-abdullakh-promo-about-me-section": LocalJSX.CntFlexyViewAbdullakhPromoAboutMeSection & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoAboutMeSectionElement>;
            "cnt-flexy-view-abdullakh-promo-animate-btn": LocalJSX.CntFlexyViewAbdullakhPromoAnimateBtn & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoAnimateBtnElement>;
            "cnt-flexy-view-abdullakh-promo-experiments": LocalJSX.CntFlexyViewAbdullakhPromoExperiments & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoExperimentsElement>;
            "cnt-flexy-view-abdullakh-promo-experiments-blocks": LocalJSX.CntFlexyViewAbdullakhPromoExperimentsBlocks & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoExperimentsBlocksElement>;
            "cnt-flexy-view-abdullakh-promo-experiments-wrapper-1_01": LocalJSX.CntFlexyViewAbdullakhPromoExperimentsWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoExperimentsWrapper1_01Element>;
            "cnt-flexy-view-abdullakh-promo-footer": LocalJSX.CntFlexyViewAbdullakhPromoFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoFooterElement>;
            "cnt-flexy-view-abdullakh-promo-footer-nav": LocalJSX.CntFlexyViewAbdullakhPromoFooterNav & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoFooterNavElement>;
            "cnt-flexy-view-abdullakh-promo-footer-wrapper-1_01": LocalJSX.CntFlexyViewAbdullakhPromoFooterWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoFooterWrapper1_01Element>;
            "cnt-flexy-view-abdullakh-promo-form-close": LocalJSX.CntFlexyViewAbdullakhPromoFormClose & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoFormCloseElement>;
            "cnt-flexy-view-abdullakh-promo-header-nav": LocalJSX.CntFlexyViewAbdullakhPromoHeaderNav & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoHeaderNavElement>;
            "cnt-flexy-view-abdullakh-promo-header-presentation": LocalJSX.CntFlexyViewAbdullakhPromoHeaderPresentation & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoHeaderPresentationElement>;
            "cnt-flexy-view-abdullakh-promo-header-social-icon": LocalJSX.CntFlexyViewAbdullakhPromoHeaderSocialIcon & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoHeaderSocialIconElement>;
            "cnt-flexy-view-abdullakh-promo-header-wrapper-1_01": LocalJSX.CntFlexyViewAbdullakhPromoHeaderWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoHeaderWrapper1_01Element>;
            "cnt-flexy-view-abdullakh-promo-latest-works": LocalJSX.CntFlexyViewAbdullakhPromoLatestWorks & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoLatestWorksElement>;
            "cnt-flexy-view-abdullakh-promo-latest-works-block": LocalJSX.CntFlexyViewAbdullakhPromoLatestWorksBlock & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoLatestWorksBlockElement>;
            "cnt-flexy-view-abdullakh-promo-latest-works-wrapper-1_01": LocalJSX.CntFlexyViewAbdullakhPromoLatestWorksWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoLatestWorksWrapper1_01Element>;
            "cnt-flexy-view-abdullakh-promo-section-about-me": LocalJSX.CntFlexyViewAbdullakhPromoSectionAboutMe & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoSectionAboutMeElement>;
            "cnt-flexy-view-abdullakh-promo-section-form": LocalJSX.CntFlexyViewAbdullakhPromoSectionForm & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhPromoSectionFormElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
